'use strict';
const async = require('async');
const config = require('config');
const FeaturedSQL = require('../db/featured');
const CollectionsSQL = require('../db/collections');
const CollectionsService = require('../services/collections');
const UtilitiesService = require('../services/utilities');
const GamesService = require('../services/games');
const Cache = require('./cache/cache.nodecache');

//default ttl of 0 (forever). Featured collections are changed only by admin actions.
const FeaturedCache = new Cache('featured');

module.exports = new (function() {

    const _self = this;
    const _defaultCollectionName = config.has('defaults.firstCollection') ? config.get('defaults.firstCollection') : '$';
    const _maxNameLength = 120;
    const _allowedSorts = {
        lastPlayed: true,
        name: true,
        playCount: true,
        releaseDate: true
    };

    //master control
    var disableAutoGeneratedMostPlayed = true;

    this.ApplicationStart = function(callback) {

        callback = callback || function() {};

        // Startup is cache warm-up only. Schema changes must be applied through migrations.
        _self.RefreshCache(callback);
    };

    // Backward-compatible name used by older application startup code. Featured collections are
    // now loaded from PostgreSQL only; this method no longer creates schema or imports files.
    this.RefreshFromFiles = function(callback) {
        _self.ApplicationStart(callback);
    };

    this.Create = function(name, gks, sortState, callback) {

        if (typeof sortState === 'function') {
            callback = sortState;
            sortState = null;
        }

        // Maintains the old development helper route, but persists through the new database-backed store.
        PublishDirect(name, gks, null, null, sortState, callback);
    };

    this.PublishUserCollection = function(userId, collectionId, orderedGameKeys, sortState, callback) {

        if (typeof sortState === 'function') {
            callback = sortState;
            sortState = null;
        }

        collectionId = ParsePositiveInteger(collectionId);
        sortState = NormalizeSortState(sortState);

        if (!userId || !collectionId) {
            return callback('Missing collection information.');
        }

        CollectionsSQL.GetCollectionById(userId, collectionId, (err, collectionRecord) => {
            if (err) { return callback(err); }

            var cleanName = NormalizeCollectionName(collectionRecord && collectionRecord.name);
            if (!cleanName || cleanName === _defaultCollectionName || cleanName === '!') {
                return callback('A named personal collection is required before it can be published as featured.');
            }

            CollectionsSQL.GetCollectionTitles(userId, collectionId, (err, titleRecords) => {
                if (err) { return callback(err); }
                if (!titleRecords || titleRecords.length < 1) {
                    return callback('Cannot publish an empty collection as featured.');
                }

                var gameKeys = BuildOrderedGameKeys(titleRecords, orderedGameKeys);

                ValidateGameKeys(gameKeys, BuildAllowedGameKeyMap(titleRecords), (err, validatedGameKeys) => {
                    if (err) { return callback(err); }
                    if (!validatedGameKeys.length) {
                        return callback('Cannot publish an empty collection as featured.');
                    }

                    FeaturedSQL.UpsertByName(cleanName, validatedGameKeys, collectionId, userId, sortState, (err, record, action) => {
                        if (err) { return callback(err); }

                        ReturnRecordAfterRefresh(record, action, callback);
                    });
                });
            });
        });
    };

    this.Delete = function(featuredCollectionId, callback) {

        featuredCollectionId = ParsePositiveInteger(featuredCollectionId);

        if (!featuredCollectionId) {
            return callback('Missing featured collection id.');
        }

        FeaturedSQL.Delete(featuredCollectionId, (err, deletedRecord) => {
            if (err) { return callback(err); }
            if (!deletedRecord) {
                return callback('Featured collection was not found.');
            }

            _self.RefreshCache((err) => {
                if (err) { return callback(err); }
                _self.Sync.ready = true;
                BuildClientCollection(deletedRecord, 0, callback);
            });
        });
    };

    this.RefreshCache = function(callback) {

        callback = callback || function() {};

        FeaturedSQL.GetActive((err, records) => {
            if (err) { return callback(err); }

            BuildClientCollections(records || [], (err, collections) => {
                if (err) { return callback(err); }

                FeaturedCache.Set([], collections, (err) => {
                    if (err) { return callback(err); }
                    callback(null, collections);
                });
            });
        });
    };

    this.GetAllCached = function(callback) {

        FeaturedCache.Get([], (err, cache) => {
            if (err) { return callback(err); }

            if (cache) {
                return callback(null, cache);
            }

            _self.RefreshCache(callback);
        });
    };

    this.GetRandom = function(opt_quantity, callback) {
        
        opt_quantity = opt_quantity || 1;

        _self.GetAllCached((err, collections) => {
            if (err) { return callback(err); }
            if (!collections || collections.length < 1) { return callback(null, []); }
            
            var random = Math.floor(Math.random() * collections.length);
            _self.GetNext(random, opt_quantity, callback);
        });
    };

    this.GetNext = function(opt_index, opt_quantity, callback) {

        opt_index = ParsePositiveInteger(opt_index);
        opt_index = opt_index || 0;
        opt_quantity = opt_quantity || 1;

        _self.GetAllCached((err, collections) => {
            if (err) { return callback(err); }
            if (!collections || collections.length < 1) { return callback(null, []); }

            var result = [];

            for (var i = 0; i < opt_quantity; ++i) {

                var index = ((i + opt_index) % collections.length);
                var collection = CloneCollection(collections[index]);
                collection.index = index;
                result.push(collection);
            }

            callback(null, result);
        });
    };

    this.CreateMostPlayed = function(system, min, max, callback) {

        if (disableAutoGeneratedMostPlayed) {
            return callback();
        }

        FeaturedSQL.GetMostPlayed(system, max, (err, results) => {
            if (err) return callback(err);

            var gameKeys = [];

            if (results.length > min) {

                var name = 'Most Played ' + results[0].system_name + ' Games';

                for (var i = 0, len = results.length; i < len; ++i) {
                    
                    var gameKey = UtilitiesService.Compress.gamekey(system, results[i].title, results[i].file);
                    gameKeys.push(gameKey);
                }

                PublishDirect(name, gameKeys, null, null, null, callback);
            }
            else {
                callback();
            }
        });
    };

    this.ToClientCollection = ToClientCollection;

    this.Sync = new (function() {
        
        var __self = this;
        this.ready = false;

        //we don't respond to incoming data about featured from the client through Sync
        this.Incoming = function() {
            return;
        };

        //outgoing is how we package one random featured collection on the server side to the client
        this.Outgoing = function(callback) {

            _self.GetRandom(1, (err, selection) => {
                if (err) return callback(err);

                // Featured collections should be selected per page load or explicit admin action,
                // not re-randomized on every unrelated sync response.
                __self.ready = false;
                callback(null, selection || []);
            });
        };

        return this;
    })();

    var PublishDirect = function(name, gks, sourceCollectionId, publishedByUserId, sortState, callback) {

        sortState = NormalizeSortState(sortState);
        var cleanName = NormalizeCollectionName(name);

        if (!cleanName || cleanName === _defaultCollectionName || cleanName === '!') {
            return callback('A featured collection name is required.');
        }

        ValidateGameKeys(gks, null, (err, validatedGameKeys) => {
            if (err) { return callback(err); }
            if (!validatedGameKeys.length) {
                return callback('Cannot publish an empty featured collection.');
            }

            FeaturedSQL.UpsertByName(cleanName, validatedGameKeys, sourceCollectionId, publishedByUserId, sortState, (err, record, action) => {
                if (err) { return callback(err); }

                ReturnRecordAfterRefresh(record, action, callback);
            });
        });
    };

    var ReturnRecordAfterRefresh = function(record, action, callback) {

        _self.RefreshCache((err) => {
            if (err) { return callback(err); }

            _self.Sync.ready = true;
            BuildClientCollection(record, 0, (err, collection) => {
                if (err) { return callback(err); }
                callback(null, collection, action);
            });
        });
    };

    var NormalizeCollectionName = function(name) {

        name = String(name || '').replace(/\.json$/i, '').trim();

        if (!name || name.length > _maxNameLength) {
            return null;
        }

        return name;
    };

    var NormalizeGameKeyList = function(gks) {

        if (!Array.isArray(gks)) {
            return [];
        }

        var result = [];
        for (var i = 0, len = gks.length; i < len; ++i) {
            if (typeof gks[i] === 'string' && gks[i].trim() !== '') {
                result.push(gks[i]);
            }
        }

        return result;
    };

    var BuildAllowedGameKeyMap = function(titleRecords) {

        var allowed = {};

        for (var i = 0, len = titleRecords.length; i < len; ++i) {
            if (titleRecords[i].game_key) {
                allowed[titleRecords[i].game_key] = true;
            }
        }

        return allowed;
    };

    var BuildOrderedGameKeys = function(titleRecords, orderedGameKeys) {

        var allowed = BuildAllowedGameKeyMap(titleRecords);
        var seen = {};
        var result = [];
        var requested = NormalizeGameKeyList(orderedGameKeys);

        for (var i = 0, len = requested.length; i < len; ++i) {
            if (allowed[requested[i]] && !seen[requested[i]]) {
                seen[requested[i]] = true;
                result.push(requested[i]);
            }
        }

        // Append any collection games that were not represented in the browser order payload.
        for (var j = 0, jlen = titleRecords.length; j < jlen; ++j) {
            var gk = titleRecords[j].game_key;
            if (gk && allowed[gk] && !seen[gk]) {
                seen[gk] = true;
                result.push(gk);
            }
        }

        return result;
    };

    var ValidateGameKeys = function(gks, allowedGameKeys, callback) {

        gks = NormalizeGameKeyList(gks);

        if (gks.length < 1) {
            return callback(null, []);
        }

        var result = [];
        var seen = {};

        async.eachSeries(gks, (gk, nextGameKey) => {

            if (seen[gk]) {
                return nextGameKey();
            }

            if (allowedGameKeys && !allowedGameKeys[gk]) {
                return nextGameKey('A game in the publish request does not belong to this collection.');
            }

            var gameKey = UtilitiesService.Decompress.gamekey(gk);
            if (!gameKey || !gameKey.gk) {
                return nextGameKey('A featured collection game identifier was invalid.');
            }

            GamesService.EnhancedGameKey(gameKey, (err) => {
                if (err) { return nextGameKey(err); }
                seen[gk] = true;
                result.push(gk);
                nextGameKey();
            });
        }, (err) => {
            if (err) { return callback(err); }
            callback(null, result);
        });
    };

    var GetRecordGameKeysEnvelope = function(record) {

        var gameKeys = record && (record.game_keys || record.gks) || [];

        if (typeof gameKeys === 'string') {
            try {
                gameKeys = JSON.parse(gameKeys);
            }
            catch (err) {
                gameKeys = [];
            }
        }

        if (gameKeys && !Array.isArray(gameKeys) && typeof gameKeys === 'object') {
            return gameKeys;
        }

        return {
            keys: gameKeys
        };
    };

    var NormalizeRecordGameKeys = function(record) {

        var envelope = GetRecordGameKeysEnvelope(record);
        var gameKeys = envelope.keys || envelope.gks || envelope.gameKeys || [];

        return NormalizeGameKeyList(gameKeys);
    };

    var NormalizeSortName = function(sort) {

        sort = String(sort || '').trim();

        if (_allowedSorts[sort]) {
            return sort;
        }

        return null;
    };

    var NormalizeSortAscending = function(asc) {

        if (asc === true || asc === false) {
            return asc;
        }

        if (asc === 'true' || asc === '1' || asc === 1) {
            return true;
        }

        if (asc === 'false' || asc === '0' || asc === 0) {
            return false;
        }

        return null;
    };

    var NormalizeSortState = function(sortState) {

        if (!sortState) {
            return {};
        }

        var sort = NormalizeSortName(sortState.sort);
        var asc = NormalizeSortAscending(sortState.asc);

        if (!sort) {
            return {};
        }

        return {
            sort: sort,
            asc: asc
        };
    };

    var BuildClientCollections = function(records, callback) {

        var collections = [];

        var next = function(index) {
            if (index >= records.length) {
                return callback(null, collections);
            }

            BuildClientCollection(records[index], index, (err, collection) => {
                if (err) { return callback(err); }
                if (collection) {
                    collections.push(collection);
                }
                next(index + 1);
            });
        };

        next(0);
    };

    var BuildClientCollection = function(record, index, callback) {

        var collection = ToClientCollection(record, index);

        if (!collection) {
            return callback(null, null);
        }

        BuildClientTitleMetadata(collection.gks, (err, titles) => {
            if (err) { return callback(err); }
            collection.titles = titles;
            callback(null, collection);
        });
    };

    var BuildClientTitleMetadata = function(gks, callback) {

        var titles = [];
        gks = NormalizeGameKeyList(gks);

        async.eachSeries(gks, (gk, nextTitle) => {
            var title = {
                gk: gk
            };

            if (!CollectionsService.GetReleaseMetadata) {
                titles.push(title);
                return nextTitle();
            }

            CollectionsService.GetReleaseMetadata(gk, (err, releaseMetadata) => {
                if (err) {
                    console.log('Featured release metadata lookup failed:', err && err.message ? err.message : err);
                }

                if (releaseMetadata) {
                    title.releaseSort = releaseMetadata.sort;
                    title.releaseLabel = releaseMetadata.label;
                }

                titles.push(title);
                nextTitle();
            });
        }, (err) => {
            if (err) { return callback(err); }
            callback(null, titles);
        });
    };

    var CloneClientTitles = function(titles) {

        var result = [];
        titles = Array.isArray(titles) ? titles : [];

        for (var i = 0, len = titles.length; i < len; ++i) {
            result.push({
                gk: titles[i].gk,
                releaseSort: titles[i].releaseSort,
                releaseLabel: titles[i].releaseLabel
            });
        }

        return result;
    };

    var GetRecordSortState = function(record) {

        var envelope = GetRecordGameKeysEnvelope(record);
        var envelopeSortState = envelope.sortState || envelope.sort_state || {};

        var sort = NormalizeSortName(envelopeSortState.sort);
        var asc = NormalizeSortAscending(envelopeSortState.asc);

        // Backward compatibility for any environment that briefly stored sort columns from
        // the earlier refinement. The game_keys envelope is preferred because it is updated
        // without requiring extra table columns.
        if (!sort) {
            sort = NormalizeSortName(record.sort);
        }

        if (asc === null) {
            asc = NormalizeSortAscending(record.asc);
        }

        return {
            sort: sort,
            asc: asc
        };
    };

    var ToClientCollection = function(record, index) {

        if (!record) {
            return null;
        }

        var id = record.featured_collection_id || record.id;
        var sortState = GetRecordSortState(record);

        return {
            id: id,
            index: typeof index === 'number' ? index : 0,
            name: record.name,
            gks: NormalizeRecordGameKeys(record),
            sort: sortState.sort,
            asc: sortState.asc,
            type: 'featured',
            readOnly: true,
            created: record.created,
            updated: record.updated
        };
    };

    var CloneCollection = function(collection) {

        return {
            id: collection.id,
            index: collection.index,
            name: collection.name,
            gks: NormalizeGameKeyList(collection.gks),
            titles: CloneClientTitles(collection.titles),
            sort: NormalizeSortName(collection.sort),
            asc: NormalizeSortAscending(collection.asc),
            type: 'featured',
            readOnly: true,
            created: collection.created,
            updated: collection.updated
        };
    };

    var ParsePositiveInteger = function(value) {

        value = parseInt(value, 10);

        if (isNaN(value) || value < 1) {
            return null;
        }

        return value;
    };

})();
