'use strict';
const async = require('async');
const config = require('config');
const FeaturedSQL = require('../db/featured');
const CollectionsSQL = require('../db/collections');
const CollectionsService = require('../services/collections');
const UtilitiesService = require('../services/utilities');
const GamesService = require('../services/games');
const FileService = require('../services/files');
const Cache = require('./cache/cache.nodecache');

//default ttl of 0 (forever). Featured collections are changed only by admin actions.
const FeaturedCache = new Cache('featured');

module.exports = new (function() {

    const _self = this;
    const _defaultCollectionName = config.has('defaults.firstCollection') ? config.get('defaults.firstCollection') : '$';
    const _maxNameLength = 120;
    const _maxImportTextBytes = 64 * 1024;
    const _maxImportGames = 500;
    const _allowedSorts = {
        lastPlayed: true,
        name: true,
        playCount: true,
        releaseDate: true
    };
    const _sortFieldOptions = [
        { value: '', label: 'Manual/import order' },
        { value: 'name', label: 'Title name' },
        { value: 'releaseDate', label: 'Release date' },
        { value: 'lastPlayed', label: 'Last played' },
        { value: 'playCount', label: 'Play count' }
    ];
    var _systemAliasMap = null;
    var _catalogCache = {};

    //master control
    var disableAutoGeneratedMostPlayed = true;

    this.ApplicationStart = function(callback) {

        callback = callback || function() {};

        // Startup is cache warm-up only. Schema changes must be applied through migrations.
        _self.RefreshCache(callback);
    };

    // Backward-compatible name used by older application startup code. Featured collections are
    // now loaded from PostgreSQL only; this method no longer creates schema or imports files.
    this.RefreshFromFiles = function(callback) {
        _self.ApplicationStart(callback);
    };

    this.Create = function(name, gks, sortState, callback) {

        if (typeof sortState === 'function') {
            callback = sortState;
            sortState = null;
        }

        // Maintains the old development helper route, but persists through the new database-backed store.
        PublishDirect(name, gks, null, null, sortState, callback);
    };

    this.CreateFromImport = function(name, importText, sortState, active, callback) {

        var cleanName = NormalizeCollectionName(name);
        var normalizedSortState = NormalizeManagementSortState(sortState);
        var isActive = NormalizeBoolean(active, true);

        if (!cleanName || cleanName === _defaultCollectionName || cleanName === '!') {
            return callback(CreateValidationError('A featured collection name is required.'));
        }

        FeaturedSQL.GetByName(cleanName, (err, existingRecord) => {
            if (err) { return callback(err); }
            if (existingRecord) {
                return callback(CreateValidationError('A featured collection with that name already exists.'));
            }

            ParseImportText(importText, (err, importResult) => {
                if (err) { return callback(err); }
                if (!importResult.gameKeys.length) {
                    return callback(CreateValidationError('Cannot create a featured collection without valid games.', importResult));
                }
                if (importResult.errors.length || importResult.unmatched.length || importResult.ambiguous.length) {
                    return callback(CreateValidationError('Some imported games could not be matched unambiguously.', importResult));
                }

                FeaturedSQL.Insert(cleanName, importResult.gameKeys, null, null, isActive, normalizedSortState, (err, record) => {
                    if (err) { return callback(err); }

                    ReturnManagementRecordAfterRefresh(record, 'insert', importResult, callback);
                });
            });
        });
    };

    this.PublishUserCollection = function(userId, collectionId, orderedGameKeys, sortState, callback) {

        if (typeof sortState === 'function') {
            callback = sortState;
            sortState = null;
        }

        collectionId = ParsePositiveInteger(collectionId);
        sortState = NormalizeSortState(sortState);

        if (!userId || !collectionId) {
            return callback('Missing collection information.');
        }

        CollectionsSQL.GetCollectionById(userId, collectionId, (err, collectionRecord) => {
            if (err) { return callback(err); }

            var cleanName = NormalizeCollectionName(collectionRecord && collectionRecord.name);
            if (!cleanName || cleanName === _defaultCollectionName || cleanName === '!') {
                return callback('A named personal collection is required before it can be published as featured.');
            }

            CollectionsSQL.GetCollectionTitles(userId, collectionId, (err, titleRecords) => {
                if (err) { return callback(err); }
                if (!titleRecords || titleRecords.length < 1) {
                    return callback('Cannot publish an empty collection as featured.');
                }

                var gameKeys = BuildOrderedGameKeys(titleRecords, orderedGameKeys);

                ValidateGameKeys(gameKeys, BuildAllowedGameKeyMap(titleRecords), (err, validatedGameKeys) => {
                    if (err) { return callback(err); }
                    if (!validatedGameKeys.length) {
                        return callback('Cannot publish an empty collection as featured.');
                    }

                    FeaturedSQL.UpsertByName(cleanName, validatedGameKeys, collectionId, userId, sortState, (err, record, action) => {
                        if (err) { return callback(err); }

                        ReturnRecordAfterRefresh(record, action, callback);
                    });
                });
            });
        });
    };

    this.GetManagementList = function(callback) {

        FeaturedSQL.GetAll((err, records) => {
            if (err) { return callback(err); }
            BuildManagementRecords(records || [], callback);
        });
    };

    this.GetSortFieldOptions = function() {
        return _sortFieldOptions.slice(0);
    };

    this.GetImportSettings = function() {
        return {
            format: 'csv',
            maxBytes: _maxImportTextBytes,
            maxGames: _maxImportGames,
            requiredHeaders: 'System,Title,File',
            alternateHeaders: 'GameKey',
            example: 'System,Title,File\nNES,Super Mario Bros.,Super Mario Bros. (W) [!].nes\nSNES,Super Mario World,Super Mario World (U) [!].smc\nGBA,Metroid - Zero Mission,Metroid - Zero Mission (U) [!].gba',
            notes: 'Rows are resolved against the Crazyerics master catalog. File may be a ROM filename or a full path; the importer uses the filename.'
        };
    };

    this.PreviewImport = function(importText, callback) {
        ParseImportText(importText, callback);
    };

    this.UpdateManagement = function(featuredCollectionId, changes, callback) {

        featuredCollectionId = ParsePositiveInteger(featuredCollectionId);
        changes = changes || {};

        if (!featuredCollectionId) {
            return callback(CreateValidationError('Missing featured collection id.'));
        }

        FeaturedSQL.GetById(featuredCollectionId, (err, record) => {
            if (err) { return callback(err); }
            if (!record) {
                return callback(CreateValidationError('Featured collection was not found.'));
            }

            var name = record.name;
            var active = IsRecordActive(record);
            var sortState = GetRecordSortState(record);
            var hasNameChange = Object.prototype.hasOwnProperty.call(changes, 'name');
            var hasActiveChange = Object.prototype.hasOwnProperty.call(changes, 'active') || Object.prototype.hasOwnProperty.call(changes, 'published') || Object.prototype.hasOwnProperty.call(changes, 'hidden');
            var hasSortChange = Object.prototype.hasOwnProperty.call(changes, 'sort') || Object.prototype.hasOwnProperty.call(changes, 'sortField') || Object.prototype.hasOwnProperty.call(changes, 'sortDirection') || Object.prototype.hasOwnProperty.call(changes, 'asc') || Object.prototype.hasOwnProperty.call(changes, 'sortState');

            if (hasNameChange) {
                name = NormalizeCollectionName(changes.name);
                if (!name || name === _defaultCollectionName || name === '!') {
                    return callback(CreateValidationError('A featured collection name is required.'));
                }
            }

            if (hasActiveChange) {
                active = NormalizePublishedState(changes, active);
                if (active === null) {
                    return callback(CreateValidationError('Published state must be true or false.'));
                }
            }

            if (hasSortChange) {
                sortState = NormalizeManagementSortState(GetSortStateFromChanges(changes));
            }

            FeaturedSQL.GetByName(name, (err, sameNameRecord) => {
                if (err) { return callback(err); }
                if (sameNameRecord && String(sameNameRecord.featured_collection_id) !== String(featuredCollectionId)) {
                    return callback(CreateValidationError('A featured collection with that name already exists.'));
                }

                FeaturedSQL.UpdateManagement(featuredCollectionId, name, NormalizeRecordGameKeys(record), active, sortState, (err, updatedRecord, action) => {
                    if (err) { return callback(err); }
                    if (!updatedRecord) {
                        return callback(CreateValidationError('Featured collection was not found.'));
                    }

                    ReturnManagementRecordAfterRefresh(updatedRecord, action || 'update', null, callback);
                });
            });
        });
    };

    this.SetActive = function(featuredCollectionId, active, callback) {
        _self.UpdateManagement(featuredCollectionId, { active: active }, callback);
    };

    this.Delete = function(featuredCollectionId, callback) {

        featuredCollectionId = ParsePositiveInteger(featuredCollectionId);

        if (!featuredCollectionId) {
            return callback('Missing featured collection id.');
        }

        FeaturedSQL.Delete(featuredCollectionId, (err, deletedRecord) => {
            if (err) { return callback(err); }
            if (!deletedRecord) {
                return callback('Featured collection was not found.');
            }

            _self.RefreshCache((err) => {
                if (err) { return callback(err); }
                _self.Sync.ready = true;
                BuildClientCollection(deletedRecord, 0, callback);
            });
        });
    };

    this.RefreshCache = function(callback) {

        callback = callback || function() {};

        FeaturedSQL.GetActive((err, records) => {
            if (err) { return callback(err); }

            BuildClientCollections(records || [], (err, collections) => {
                if (err) { return callback(err); }

                FeaturedCache.Set([], collections, (err) => {
                    if (err) { return callback(err); }
                    callback(null, collections);
                });
            });
        });
    };

    this.GetAllCached = function(callback) {

        FeaturedCache.Get([], (err, cache) => {
            if (err) { return callback(err); }

            if (cache) {
                return callback(null, cache);
            }

            _self.RefreshCache(callback);
        });
    };

    this.GetRandom = function(opt_quantity, callback) {
        
        opt_quantity = opt_quantity || 1;

        _self.GetAllCached((err, collections) => {
            if (err) { return callback(err); }
            if (!collections || collections.length < 1) { return callback(null, []); }
            
            var random = Math.floor(Math.random() * collections.length);
            _self.GetNext(random, opt_quantity, callback);
        });
    };

    this.GetNext = function(opt_index, opt_quantity, callback) {

        opt_index = ParsePositiveInteger(opt_index);
        opt_index = opt_index || 0;
        opt_quantity = opt_quantity || 1;

        _self.GetAllCached((err, collections) => {
            if (err) { return callback(err); }
            if (!collections || collections.length < 1) { return callback(null, []); }

            var result = [];

            for (var i = 0; i < opt_quantity; ++i) {

                var index = ((i + opt_index) % collections.length);
                var collection = CloneCollection(collections[index]);
                collection.index = index;
                result.push(collection);
            }

            callback(null, result);
        });
    };

    this.CreateMostPlayed = function(system, min, max, callback) {

        if (disableAutoGeneratedMostPlayed) {
            return callback();
        }

        FeaturedSQL.GetMostPlayed(system, max, (err, results) => {
            if (err) return callback(err);

            var gameKeys = [];

            if (results.length > min) {

                var name = 'Most Played ' + results[0].system_name + ' Games';

                for (var i = 0, len = results.length; i < len; ++i) {
                    
                    var gameKey = UtilitiesService.Compress.gamekey(system, results[i].title, results[i].file);
                    gameKeys.push(gameKey);
                }

                PublishDirect(name, gameKeys, null, null, null, callback);
            }
            else {
                callback();
            }
        });
    };

    this.ToClientCollection = ToClientCollection;

    this.Sync = new (function() {
        
        var __self = this;
        this.ready = false;

        //we don't respond to incoming data about featured from the client through Sync
        this.Incoming = function() {
            return;
        };

        //outgoing is how we package one random featured collection on the server side to the client
        this.Outgoing = function(callback) {

            _self.GetRandom(1, (err, selection) => {
                if (err) return callback(err);

                // Featured collections should be selected per page load or explicit admin action,
                // not re-randomized on every unrelated sync response.
                __self.ready = false;
                callback(null, selection || []);
            });
        };

        return this;
    })();

    var PublishDirect = function(name, gks, sourceCollectionId, publishedByUserId, sortState, callback) {

        sortState = NormalizeSortState(sortState);
        var cleanName = NormalizeCollectionName(name);

        if (!cleanName || cleanName === _defaultCollectionName || cleanName === '!') {
            return callback('A featured collection name is required.');
        }

        ValidateGameKeys(gks, null, (err, validatedGameKeys) => {
            if (err) { return callback(err); }
            if (!validatedGameKeys.length) {
                return callback('Cannot publish an empty featured collection.');
            }

            FeaturedSQL.UpsertByName(cleanName, validatedGameKeys, sourceCollectionId, publishedByUserId, sortState, (err, record, action) => {
                if (err) { return callback(err); }

                ReturnRecordAfterRefresh(record, action, callback);
            });
        });
    };

    var ReturnRecordAfterRefresh = function(record, action, callback) {

        _self.RefreshCache((err) => {
            if (err) { return callback(err); }

            _self.Sync.ready = true;
            BuildClientCollection(record, 0, (err, collection) => {
                if (err) { return callback(err); }
                callback(null, collection, action);
            });
        });
    };

    var ReturnManagementRecordAfterRefresh = function(record, action, importResult, callback) {

        _self.RefreshCache((err) => {
            if (err) { return callback(err); }

            _self.Sync.ready = true;
            BuildManagementRecord(record, (err, managementRecord) => {
                if (err) { return callback(err); }
                callback(null, managementRecord, action, importResult);
            });
        });
    };

    var NormalizeCollectionName = function(name) {

        name = String(name || '').replace(/\.json$/i, '').replace(/\s+/g, ' ').trim();

        if (!name || name.length > _maxNameLength) {
            return null;
        }

        return name;
    };

    var NormalizeGameKeyList = function(gks) {

        if (!Array.isArray(gks)) {
            return [];
        }

        var result = [];
        for (var i = 0, len = gks.length; i < len; ++i) {
            var gameKey = NormalizeGameReferenceToGameKey(gks[i]);
            if (gameKey) {
                result.push(gameKey);
            }
        }

        return result;
    };

    var NormalizeGameReferenceToGameKey = function(value) {

        var system;
        var title;
        var file;

        if (typeof value === 'string') {
            value = value.trim();
            return value || null;
        }

        if (!value || typeof value !== 'object') {
            return null;
        }

        if (typeof value.gk === 'string' && value.gk.trim()) {
            return value.gk.trim();
        }

        if (typeof value.gameKey === 'string' && value.gameKey.trim()) {
            return value.gameKey.trim();
        }

        system = value.system || value.systemId || value.system_id;
        title = value.title || value.name;
        file = value.file || value.rom || value.romFile || value.rom_file || value.romPath || value.rom_path;

        system = NormalizeImportField(system);
        title = NormalizeImportField(title);
        file = NormalizeImportedRomFilename(file);

        if (!system || !title || !file) {
            return null;
        }

        return UtilitiesService.Compress.gamekey(system, title, file);
    };

    var BuildAllowedGameKeyMap = function(titleRecords) {

        var allowed = {};

        for (var i = 0, len = titleRecords.length; i < len; ++i) {
            if (titleRecords[i].game_key) {
                allowed[titleRecords[i].game_key] = true;
            }
        }

        return allowed;
    };

    var BuildOrderedGameKeys = function(titleRecords, orderedGameKeys) {

        var allowed = BuildAllowedGameKeyMap(titleRecords);
        var seen = {};
        var result = [];
        var requested = NormalizeGameKeyList(orderedGameKeys);

        for (var i = 0, len = requested.length; i < len; ++i) {
            if (allowed[requested[i]] && !seen[requested[i]]) {
                seen[requested[i]] = true;
                result.push(requested[i]);
            }
        }

        // Append any collection games that were not represented in the browser order payload.
        for (var j = 0, jlen = titleRecords.length; j < jlen; ++j) {
            var gk = titleRecords[j].game_key;
            if (gk && allowed[gk] && !seen[gk]) {
                seen[gk] = true;
                result.push(gk);
            }
        }

        return result;
    };

    var ValidateGameKeys = function(gks, allowedGameKeys, callback) {

        gks = NormalizeGameKeyList(gks);

        if (gks.length < 1) {
            return callback(null, []);
        }

        var result = [];
        var seen = {};

        async.eachSeries(gks, (gk, nextGameKey) => {

            if (seen[gk]) {
                return nextGameKey();
            }

            if (allowedGameKeys && !allowedGameKeys[gk]) {
                return nextGameKey('A game in the publish request does not belong to this collection.');
            }

            var gameKey = UtilitiesService.Decompress.gamekey(gk);
            if (!gameKey || !gameKey.gk) {
                return nextGameKey('A featured collection game identifier was invalid.');
            }

            GamesService.EnhancedGameKey(gameKey, (err) => {
                if (err) { return nextGameKey(err); }
                seen[gk] = true;
                result.push(gk);
                nextGameKey();
            });
        }, (err) => {
            if (err) { return callback(err); }
            callback(null, result);
        });
    };

    var GetRecordGameKeysEnvelope = function(record) {

        var gameKeys = record && (record.game_keys || record.gks) || [];

        if (typeof gameKeys === 'string') {
            try {
                gameKeys = JSON.parse(gameKeys);
            }
            catch (err) {
                gameKeys = [];
            }
        }

        if (gameKeys && !Array.isArray(gameKeys) && typeof gameKeys === 'object') {
            return gameKeys;
        }

        return {
            keys: gameKeys
        };
    };

    var NormalizeRecordGameKeys = function(record) {

        var envelope = GetRecordGameKeysEnvelope(record);
        var gameKeys = envelope.keys || envelope.gks || envelope.gameKeys || envelope.games || envelope.titles || envelope.items || [];

        return NormalizeGameKeyList(gameKeys);
    };

    var NormalizeSortName = function(sort) {

        sort = String(sort || '').trim();

        if (sort === 'manual') {
            return null;
        }

        if (_allowedSorts[sort]) {
            return sort;
        }

        return null;
    };

    var NormalizeSortAscending = function(asc) {

        if (asc === true || asc === false) {
            return asc;
        }

        if (asc === 'true' || asc === '1' || asc === 1 || asc === 'asc' || asc === 'ASC') {
            return true;
        }

        if (asc === 'false' || asc === '0' || asc === 0 || asc === 'desc' || asc === 'DESC') {
            return false;
        }

        return null;
    };

    var NormalizeSortState = function(sortState) {

        if (!sortState) {
            return {};
        }

        var sort = NormalizeSortName(sortState.sort);
        var asc = NormalizeSortAscending(sortState.asc);

        if (!sort) {
            return {};
        }

        return {
            sort: sort,
            asc: asc
        };
    };

    var NormalizeManagementSortState = function(sortState) {

        if (!sortState) {
            return {};
        }

        var sort = NormalizeSortName(sortState.sort);
        var asc = NormalizeSortAscending(sortState.asc);

        if (!sort) {
            return {};
        }

        return {
            sort: sort,
            asc: asc === false ? false : true
        };
    };

    var GetSortStateFromChanges = function(changes) {

        var sortState = changes.sortState || {};
        var sort = Object.prototype.hasOwnProperty.call(changes, 'sort') ? changes.sort : sortState.sort;
        var asc = Object.prototype.hasOwnProperty.call(changes, 'asc') ? changes.asc : sortState.asc;
        var direction = Object.prototype.hasOwnProperty.call(changes, 'sortDirection') ? changes.sortDirection : sortState.sortDirection;

        if (Object.prototype.hasOwnProperty.call(changes, 'sortField')) {
            sort = changes.sortField;
        }

        if (typeof direction !== 'undefined') {
            asc = String(direction).toLowerCase() !== 'desc';
        }

        return {
            sort: sort,
            asc: asc
        };
    };

    var BuildClientCollections = function(records, callback) {

        var collections = [];

        var next = function(index) {
            if (index >= records.length) {
                return callback(null, collections);
            }

            BuildClientCollection(records[index], index, (err, collection) => {
                if (err) { return callback(err); }
                if (collection) {
                    collections.push(collection);
                }
                next(index + 1);
            });
        };

        next(0);
    };

    var BuildClientCollection = function(record, index, callback) {

        var collection = ToClientCollection(record, index);

        if (!collection) {
            return callback(null, null);
        }

        HydrateGameKeys(collection.gks, (err, hydration) => {
            if (err) { return callback(err); }

            collection.gks = hydration.gameKeys;

            if (!collection.gks.length) {
                if (hydration.invalid.length) {
                    console.log('Featured collection "' + (collection.name || collection.id) + '" has no hydratable games and will be hidden from the public payload.');
                }
                return callback(null, null);
            }

            BuildClientTitleMetadata(collection.gks, (err, titles) => {
                if (err) { return callback(err); }
                collection.titles = titles;
                callback(null, collection);
            });
        });
    };

    var BuildClientTitleMetadata = function(gks, callback) {

        var titles = [];
        gks = NormalizeGameKeyList(gks);

        async.eachSeries(gks, (gk, nextTitle) => {
            var title = {
                gk: gk
            };

            var finishTitle = function() {
                GetFeaturedGameStats(gk, (statsErr, stats) => {
                    if (statsErr) {
                        console.log('Featured play-stat metadata lookup failed:', statsErr && statsErr.message ? statsErr.message : statsErr);
                    }

                    if (stats) {
                        title.playCount = stats.playCount;
                        title.lastPlayed = stats.lastPlayed;
                    }
                    else {
                        title.playCount = 0;
                        title.lastPlayed = -1;
                    }

                    titles.push(title);
                    nextTitle();
                });
            };

            if (!CollectionsService.GetReleaseMetadata) {
                return finishTitle();
            }

            CollectionsService.GetReleaseMetadata(gk, (err, releaseMetadata) => {
                if (err) {
                    console.log('Featured release metadata lookup failed:', err && err.message ? err.message : err);
                }

                if (releaseMetadata) {
                    title.releaseSort = releaseMetadata.sort;
                    title.releaseLabel = releaseMetadata.label;
                }

                finishTitle();
            });
        }, (err) => {
            if (err) { return callback(err); }
            callback(null, titles);
        });
    };

    var GetFeaturedGameStats = function(gk, callback) {

        var gameKey;

        try {
            gameKey = UtilitiesService.Decompress.gamekey(gk);
        }
        catch (err) {
            return callback(null, null);
        }

        if (!gameKey || !gameKey.system || !gameKey.title || !gameKey.file) {
            return callback(null, null);
        }

        FeaturedSQL.GetFileStats(gameKey.system, gameKey.title, gameKey.file, (err, record) => {
            if (err) { return callback(err); }
            if (!record) { return callback(null, null); }

            callback(null, {
                playCount: ParseIntegerOrDefault(record.play_count, 0),
                lastPlayed: ParseDateSortValue(record.last_played, -1)
            });
        });
    };

    var CloneClientTitles = function(titles) {

        var result = [];
        titles = Array.isArray(titles) ? titles : [];

        for (var i = 0, len = titles.length; i < len; ++i) {
            result.push({
                gk: titles[i].gk,
                releaseSort: titles[i].releaseSort,
                releaseLabel: titles[i].releaseLabel,
                playCount: ParseIntegerOrDefault(titles[i].playCount, 0),
                lastPlayed: ParseIntegerOrDefault(titles[i].lastPlayed, -1)
            });
        }

        return result;
    };

    var GetRecordSortState = function(record) {

        var envelope = GetRecordGameKeysEnvelope(record);
        var envelopeSortState = envelope.sortState || envelope.sort_state || {};

        var sort = NormalizeSortName(envelopeSortState.sort);
        var asc = NormalizeSortAscending(envelopeSortState.asc);

        // Backward compatibility for any environment that briefly stored sort columns from
        // the earlier refinement. The game_keys envelope is preferred because it is updated
        // without requiring extra table columns.
        if (!sort) {
            sort = NormalizeSortName(record.sort);
        }

        if (asc === null) {
            asc = NormalizeSortAscending(record.asc);
        }

        return {
            sort: sort,
            asc: asc
        };
    };

    var ToClientCollection = function(record, index) {

        if (!record) {
            return null;
        }

        var id = record.featured_collection_id || record.id;
        var sortState = GetRecordSortState(record);

        return {
            id: id,
            index: typeof index === 'number' ? index : 0,
            name: record.name,
            gks: NormalizeRecordGameKeys(record),
            sort: sortState.sort,
            asc: sortState.asc,
            type: 'featured',
            readOnly: true,
            active: IsRecordActive(record),
            created: record.created,
            updated: record.updated
        };
    };

    var CloneCollection = function(collection) {

        return {
            id: collection.id,
            index: collection.index,
            name: collection.name,
            gks: NormalizeGameKeyList(collection.gks),
            titles: CloneClientTitles(collection.titles),
            sort: NormalizeSortName(collection.sort),
            asc: NormalizeSortAscending(collection.asc),
            type: 'featured',
            readOnly: true,
            active: collection.active === false ? false : true,
            created: collection.created,
            updated: collection.updated
        };
    };

    var BuildManagementRecords = function(records, callback) {

        var result = [];

        async.eachSeries(records, (record, nextRecord) => {
            BuildManagementRecord(record, (err, managementRecord) => {
                if (err) { return nextRecord(err); }
                result.push(managementRecord);
                nextRecord();
            });
        }, (err) => {
            if (err) { return callback(err); }
            callback(null, result);
        });
    };

    var BuildManagementRecord = function(record, callback) {

        var rawGameKeys = NormalizeRecordGameKeys(record);
        var sortState = GetRecordSortState(record);
        var active = IsRecordActive(record);

        HydrateGameKeys(rawGameKeys, (err, hydration) => {
            if (err) { return callback(err); }

            var preview = [];
            var previewLimit = Math.min(5, hydration.matched.length);

            for (var i = 0; i < previewLimit; ++i) {
                preview.push({
                    system: hydration.matched[i].system,
                    title: hydration.matched[i].title,
                    file: hydration.matched[i].file,
                    gameKey: hydration.matched[i].gameKey
                });
            }

            callback(null, {
                id: record.featured_collection_id || record.id,
                name: record.name,
                active: active,
                published: active,
                hidden: !active,
                status: active ? 'published' : 'hidden',
                gameCount: hydration.gameKeys.length,
                rawGameCount: rawGameKeys.length,
                invalidGameCount: hydration.invalid.length,
                duplicateGameCount: hydration.duplicates.length,
                sort: sortState.sort || '',
                sortField: sortState.sort || '',
                asc: sortState.asc === false ? false : true,
                sortDirection: sortState.asc === false ? 'desc' : 'asc',
                created: record.created,
                updated: record.updated,
                sourceCollectionId: record.source_collection_id || null,
                publishedByUserId: record.published_by_user_id || null,
                preview: preview,
                warnings: BuildManagementWarnings(hydration)
            });
        });
    };

    var DecodeGameKeyForDisplay = function(gk) {

        var gameKey;

        try {
            gameKey = UtilitiesService.Decompress.gamekey(gk);
        }
        catch (err) {
            return {
                gameKey: gk,
                invalid: true
            };
        }

        if (!gameKey) {
            return {
                gameKey: gk,
                invalid: true
            };
        }

        return {
            system: gameKey.system,
            title: gameKey.title,
            file: gameKey.file,
            gameKey: gk
        };
    };

    var ParseImportText = function(importText, callback) {

        var text = String(importText || '');

        if (!text.trim()) {
            return callback(CreateValidationError('Import text is required.'));
        }

        if (Buffer.byteLength(text, 'utf8') > _maxImportTextBytes) {
            return callback(CreateValidationError('Import text is too large.'));
        }

        var rows;

        try {
            rows = ParseCsvImportRows(text);
        }
        catch (err) {
            return callback(CreateValidationError(err && err.message ? err.message : 'Import CSV could not be parsed.'));
        }

        if (!rows.length) {
            return callback(CreateValidationError('Import CSV must include at least one game row.'));
        }

        ValidateImportRows(rows, callback);
    };

    var ParseCsvImportRows = function(text) {

        var lines = String(text || '').replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');
        var contentLines = [];
        var headerFields;
        var normalizedHeaders;
        var rows = [];

        for (var i = 0; i < lines.length; ++i) {
            if (!lines[i].trim() || lines[i].trim().charAt(0) === '#') {
                continue;
            }

            contentLines.push({
                number: i + 1,
                text: lines[i]
            });
        }

        if (contentLines.length < 2) {
            throw new Error('Import CSV must include a header row and at least one game row.');
        }

        headerFields = ParseCsvLine(contentLines[0].text);
        normalizedHeaders = headerFields.map(NormalizeCsvHeader);

        if (!HasHeader(normalizedHeaders, ['gamekey', 'gk']) && !(HasHeader(normalizedHeaders, ['system', 'systemid']) && HasHeader(normalizedHeaders, ['title', 'name']) && HasHeader(normalizedHeaders, ['file', 'rom', 'romfile', 'rompath']))) {
            throw new Error('Import CSV headers must include either gameKey or system,title,file.');
        }

        for (var rowIndex = 1; rowIndex < contentLines.length; ++rowIndex) {
            var fields = ParseCsvLine(contentLines[rowIndex].text);
            var values = {};
            var allEmpty = true;

            for (var fieldIndex = 0; fieldIndex < normalizedHeaders.length; ++fieldIndex) {
                values[normalizedHeaders[fieldIndex]] = typeof fields[fieldIndex] === 'undefined' ? '' : String(fields[fieldIndex]).trim();
                if (values[normalizedHeaders[fieldIndex]]) {
                    allEmpty = false;
                }
            }

            if (!allEmpty) {
                rows.push({
                    line: contentLines[rowIndex].number,
                    values: values,
                    raw: contentLines[rowIndex].text
                });
            }
        }

        return rows;
    };

    var ParseCsvLine = function(line) {

        var result = [];
        var current = '';
        var inQuotes = false;

        line = String(line || '');

        for (var i = 0; i < line.length; ++i) {
            var ch = line.charAt(i);

            if (ch === '"') {
                if (inQuotes && line.charAt(i + 1) === '"') {
                    current += '"';
                    i++;
                }
                else {
                    inQuotes = !inQuotes;
                }
            }
            else if (ch === ',' && !inQuotes) {
                result.push(current);
                current = '';
            }
            else {
                current += ch;
            }
        }

        if (inQuotes) {
            throw new Error('Import CSV contains an unterminated quoted value.');
        }

        result.push(current);
        return result;
    };

    var NormalizeCsvHeader = function(header) {
        return String(header || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');
    };

    var HasHeader = function(headers, aliases) {

        for (var i = 0; i < aliases.length; ++i) {
            if (headers.indexOf(aliases[i]) >= 0) {
                return true;
            }
        }

        return false;
    };

    var GetCsvValue = function(row, aliases) {

        for (var i = 0; i < aliases.length; ++i) {
            if (row.values.hasOwnProperty(aliases[i]) && row.values[aliases[i]]) {
                return row.values[aliases[i]];
            }
        }

        return '';
    };

    var ValidateImportRows = function(rows, callback) {

        var result = {
            totalRows: rows.length,
            gameKeys: [],
            matched: [],
            unmatched: [],
            ambiguous: [],
            duplicates: [],
            errors: [],
            maxGames: _maxImportGames
        };
        var seen = {};

        async.eachSeries(rows, (row, nextRow) => {
            if (result.gameKeys.length >= _maxImportGames) {
                result.errors.push({
                    line: row.line,
                    error: 'Skipped because the import limit is ' + _maxImportGames + ' games.'
                });
                return nextRow();
            }

            ResolveImportRow(row, (err, match) => {
                if (err) { return nextRow(err); }

                if (!match || match.error) {
                    AppendImportIssue(result, row, match);
                    return nextRow();
                }

                if (seen[match.gameKey]) {
                    result.duplicates.push({
                        line: row.line,
                        firstLine: seen[match.gameKey],
                        system: match.system,
                        systemKey: match.systemKey,
                        title: match.title,
                        file: match.file,
                        gameKey: match.gameKey,
                        error: 'Duplicate game reference ignored.'
                    });
                    return nextRow();
                }

                seen[match.gameKey] = row.line;
                result.gameKeys.push(match.gameKey);
                result.matched.push(match);
                nextRow();
            });
        }, (err) => {
            if (err) { return callback(err); }
            callback(null, result);
        });
    };

    var AppendImportIssue = function(result, row, match) {

        var issue = {
            line: row && row.line,
            system: match && match.system,
            title: match && match.title,
            file: match && match.file,
            error: match && match.error ? match.error : 'Game could not be matched.'
        };

        if (match && match.systemKey) {
            issue.systemKey = match.systemKey;
        }

        if (match && match.candidates) {
            issue.candidates = match.candidates;
        }

        if (match && match.errorType === 'ambiguous') {
            result.ambiguous.push(issue);
        }
        else if (match && match.errorType === 'malformed') {
            result.errors.push(issue);
        }
        else {
            result.unmatched.push(issue);
        }
    };

    var ResolveImportRow = function(row, callback) {

        var gameKeyValue = GetCsvValue(row, ['gamekey', 'gk']);
        var system = GetCsvValue(row, ['system', 'systemid']);
        var title = GetCsvValue(row, ['title', 'name']);
        var file = GetCsvValue(row, ['file', 'rom', 'romfile', 'rompath']);
        var gameKey;

        if (gameKeyValue) {
            try {
                gameKey = UtilitiesService.Decompress.gamekey(gameKeyValue);
            }
            catch (err) {
                return callback(null, BuildResolutionIssue('malformed', 'Invalid compressed gameKey value.', system, title, file));
            }

            if (!gameKey || !gameKey.system || !gameKey.title || !gameKey.file) {
                return callback(null, BuildResolutionIssue('malformed', 'Invalid compressed gameKey value.', system, title, file));
            }

            system = gameKey.system;
            title = gameKey.title;
            file = gameKey.file;
        }

        system = NormalizeImportField(system);
        title = NormalizeImportField(title);
        file = NormalizeImportedRomFilename(file);

        if (!system || (!title && !file)) {
            return callback(null, BuildResolutionIssue('malformed', 'Each row requires system plus a ROM file and/or title, or a gameKey.', system, title, file));
        }

        ResolveCanonicalGame(system, title, file, (err, resolution) => {
            if (err) { return callback(err); }
            if (!resolution || !resolution.ok) {
                return callback(null, resolution || BuildResolutionIssue('unmatched', 'Game could not be matched.', system, title, file));
            }

            callback(null, {
                line: row.line,
                system: resolution.system,
                systemKey: resolution.systemKey,
                title: resolution.title,
                file: resolution.file,
                gameKey: resolution.gameKey,
                matchMethod: resolution.matchMethod,
                input: {
                    system: system,
                    title: title,
                    file: file,
                    gameKey: gameKeyValue || null
                }
            });
        });
    };

    var ResolveCompressedGameKey = function(gk, callback) {

        var gameKey;

        try {
            gameKey = UtilitiesService.Decompress.gamekey(gk);
        }
        catch (err) {
            return callback(null, BuildResolutionIssue('malformed', 'Invalid compressed gameKey value.'));
        }

        if (!gameKey || !gameKey.system || !gameKey.title || !gameKey.file) {
            return callback(null, BuildResolutionIssue('malformed', 'Invalid compressed gameKey value.'));
        }

        ResolveCanonicalGame(gameKey.system, gameKey.title, gameKey.file, callback);
    };

    var ResolveCanonicalGame = function(systemInput, titleInput, fileInput, callback) {

        var systemResolution = ResolveSystemKey(systemInput);
        var systemKey;
        var normalizedTitle;
        var normalizedFile;

        titleInput = NormalizeImportField(titleInput);
        fileInput = NormalizeImportedRomFilename(fileInput);

        if (!systemResolution.ok) {
            return callback(null, BuildResolutionIssue(systemResolution.errorType, systemResolution.error, systemInput, titleInput, fileInput));
        }

        systemKey = systemResolution.systemKey;
        normalizedTitle = titleInput;
        normalizedFile = fileInput;

        GetSystemCatalog(systemKey, (err, catalog) => {
            if (err) { return callback(err); }
            if (!catalog) {
                return callback(null, BuildResolutionIssue('unmatched', 'System "' + systemInput + '" was not found.', systemInput, normalizedTitle, normalizedFile));
            }

            var fileMatches = normalizedFile ? FindCatalogEntriesByFile(catalog, normalizedFile) : [];
            var titleResolution;
            var titleFiltered;

            if (fileMatches.length) {
                if (normalizedTitle) {
                    titleFiltered = FilterEntriesByTitle(catalog, fileMatches, normalizedTitle);

                    if (titleFiltered.ambiguous) {
                        return callback(null, BuildResolutionIssue('ambiguous', titleFiltered.error, systemInput, normalizedTitle, normalizedFile, titleFiltered.candidates));
                    }

                    if (titleFiltered.entries.length === 1) {
                        return callback(null, BuildResolvedCatalogEntry(titleFiltered.entries[0], 'system-file-title'));
                    }

                    if (titleFiltered.entries.length > 1) {
                        return callback(null, BuildResolutionIssue('ambiguous', 'The ROM filename and title matched multiple catalog games.', systemInput, normalizedTitle, normalizedFile, titleFiltered.entries));
                    }
                }

                if (fileMatches.length === 1) {
                    return callback(null, BuildResolvedCatalogEntry(fileMatches[0], 'system-file'));
                }

                return callback(null, BuildResolutionIssue('ambiguous', 'The ROM filename matched multiple catalog games. Add or correct the title to disambiguate.', systemInput, normalizedTitle, normalizedFile, fileMatches));
            }

            if (normalizedTitle) {
                titleResolution = FindCatalogEntriesByTitle(catalog, normalizedTitle);

                if (titleResolution.ambiguous) {
                    return callback(null, BuildResolutionIssue('ambiguous', titleResolution.error, systemInput, normalizedTitle, normalizedFile, titleResolution.candidates));
                }

                if (titleResolution.entries.length) {
                    if (normalizedFile) {
                        return callback(null, BuildResolutionIssue('unmatched', 'File "' + normalizedFile + '" was not found for matched title "' + titleResolution.title + '".', systemInput, titleResolution.title, normalizedFile));
                    }

                    var preferredEntry = SelectPreferredTitleEntry(titleResolution.entries);
                    if (preferredEntry.ambiguous) {
                        return callback(null, BuildResolutionIssue('ambiguous', preferredEntry.error, systemInput, titleResolution.title, normalizedFile, preferredEntry.candidates));
                    }

                    return callback(null, BuildResolvedCatalogEntry(preferredEntry.entry, 'system-title'));
                }
            }

            if (normalizedFile) {
                return callback(null, BuildResolutionIssue('unmatched', 'File "' + normalizedFile + '" was not found for system "' + GetSystemDisplayKey(systemKey) + '".', systemInput, normalizedTitle, normalizedFile));
            }

            callback(null, BuildResolutionIssue('unmatched', 'Title "' + normalizedTitle + '" was not found for system "' + GetSystemDisplayKey(systemKey) + '".', systemInput, normalizedTitle, normalizedFile));
        });
    };

    var HydrateGameKeys = function(gks, callback) {

        var result = {
            gameKeys: [],
            matched: [],
            invalid: [],
            duplicates: []
        };
        var seen = {};

        gks = NormalizeGameKeyList(gks);

        async.eachSeries(gks, (gk, nextGameKey) => {
            ResolveCompressedGameKey(gk, (err, resolution) => {
                if (err) { return nextGameKey(err); }

                if (!resolution || !resolution.ok) {
                    result.invalid.push({
                        gameKey: gk,
                        error: resolution && resolution.error ? resolution.error : 'Stored featured game could not be hydrated.',
                        system: resolution && resolution.system,
                        title: resolution && resolution.title,
                        file: resolution && resolution.file
                    });
                    return nextGameKey();
                }

                if (seen[resolution.gameKey]) {
                    result.duplicates.push({
                        gameKey: resolution.gameKey,
                        firstLine: seen[resolution.gameKey],
                        system: resolution.system,
                        title: resolution.title,
                        file: resolution.file,
                        error: 'Duplicate stored game reference ignored.'
                    });
                    return nextGameKey();
                }

                seen[resolution.gameKey] = result.gameKeys.length + 1;
                result.gameKeys.push(resolution.gameKey);
                result.matched.push(resolution);
                nextGameKey();
            });
        }, (err) => {
            if (err) { return callback(err); }
            callback(null, result);
        });
    };

    var BuildManagementWarnings = function(hydration) {

        var warnings = [];

        hydration = hydration || {};

        if (hydration.invalid && hydration.invalid.length) {
            warnings.push(hydration.invalid.length + ' stored game reference' + (hydration.invalid.length === 1 ? '' : 's') + ' could not be hydrated and will be hidden from public featured results.');
        }

        if (hydration.duplicates && hydration.duplicates.length) {
            warnings.push(hydration.duplicates.length + ' duplicate stored game reference' + (hydration.duplicates.length === 1 ? '' : 's') + ' ignored during hydration.');
        }

        return warnings;
    };

    var ResolveSystemKey = function(systemInput) {

        var aliasMap = GetSystemAliasMap();
        var keys = BuildSystemLookupKeys(systemInput);
        var matches = [];
        var seen = {};

        for (var i = 0; i < keys.length; ++i) {
            var value = aliasMap[keys[i]];
            if (value && !seen[value]) {
                seen[value] = true;
                matches.push(value);
            }
            else if (value === false) {
                return {
                    ok: false,
                    errorType: 'ambiguous',
                    error: 'System "' + systemInput + '" matched multiple configured systems.'
                };
            }
        }

        if (matches.length === 1) {
            return {
                ok: true,
                systemKey: matches[0]
            };
        }

        if (matches.length > 1) {
            return {
                ok: false,
                errorType: 'ambiguous',
                error: 'System "' + systemInput + '" matched multiple configured systems.'
            };
        }

        return {
            ok: false,
            errorType: 'unmatched',
            error: 'System "' + systemInput + '" was not found.'
        };
    };

    var GetSystemAliasMap = function() {

        if (_systemAliasMap) {
            return _systemAliasMap;
        }

        var systems = config.has('systems') ? config.get('systems') : {};
        var map = {};

        Object.keys(systems || {}).forEach(function(systemKey) {
            var systemConfig = systems[systemKey] || {};

            if (!systemKey || systemKey === 'default') {
                return;
            }

            AddSystemAlias(map, systemKey, systemKey);
            AddSystemAlias(map, systemKey, systemKey.toUpperCase());
            AddSystemAlias(map, systemKey, systemConfig.name);
            AddSystemAlias(map, systemKey, systemConfig.shortname);
            AddSystemAlias(map, systemKey, systemConfig.shortName);
            AddSystemAlias(map, systemKey, systemConfig.abbreviation);
            AddSystemAlias(map, systemKey, systemConfig.abbr);
            AddSystemAlias(map, systemKey, systemConfig.shortkey);
            AddSystemAlias(map, systemKey, systemConfig.shortKey);
        });

        _systemAliasMap = map;
        return _systemAliasMap;
    };

    var AddSystemAlias = function(map, systemKey, alias) {

        var keys = BuildSystemLookupKeys(alias);

        for (var i = 0; i < keys.length; ++i) {
            if (!keys[i]) {
                continue;
            }

            if (map.hasOwnProperty(keys[i]) && map[keys[i]] !== systemKey) {
                map[keys[i]] = false;
            }
            else {
                map[keys[i]] = systemKey;
            }
        }
    };

    var BuildSystemLookupKeys = function(value) {

        var normalized = NormalizeSystemLookupText(value);
        var compact = normalized.replace(/[^a-z0-9]/g, '');
        var keys = [];

        if (normalized) {
            keys.push(normalized);
        }

        if (compact && compact !== normalized) {
            keys.push(compact);
        }

        return keys;
    };

    var NormalizeSystemLookupText = function(value) {
        return String(value || '')
            .toLowerCase()
            .replace(/&/g, ' and ')
            .replace(/[^a-z0-9]+/g, ' ')
            .replace(/\s+/g, ' ')
            .trim();
    };

    var GetSystemCatalog = function(systemKey, callback) {

        if (_catalogCache[systemKey]) {
            return callback(null, _catalogCache[systemKey]);
        }

        FileService.Get('/data/' + systemKey + '_master', (err, masterFile) => {
            if (err || !masterFile) {
                return callback(null, null);
            }

            var catalog = BuildSystemCatalog(systemKey, masterFile);
            _catalogCache[systemKey] = catalog;
            callback(null, catalog);
        });
    };

    var BuildSystemCatalog = function(systemKey, masterFile) {

        var catalog = {
            systemKey: systemKey,
            system: GetSystemDisplayKey(systemKey),
            entries: [],
            fileExact: {},
            fileNormalized: {},
            titleExact: {},
            titleNormalized: {},
            titleNamesByNormalized: {}
        };

        Object.keys(masterFile || {}).forEach(function(title) {
            var titleRecord = masterFile[title] || {};
            var files = titleRecord.f || {};
            var normalizedTitle = NormalizeTitleLookupText(title);

            if (!catalog.titleExact[title]) {
                catalog.titleExact[title] = [];
            }

            if (normalizedTitle) {
                if (!catalog.titleNamesByNormalized[normalizedTitle]) {
                    catalog.titleNamesByNormalized[normalizedTitle] = [];
                }
                if (catalog.titleNamesByNormalized[normalizedTitle].indexOf(title) < 0) {
                    catalog.titleNamesByNormalized[normalizedTitle].push(title);
                }
            }

            Object.keys(files).forEach(function(file) {
                var entry = {
                    system: catalog.system,
                    systemKey: systemKey,
                    title: title,
                    file: file,
                    fileBasename: NormalizeImportedRomFilename(file),
                    best: titleRecord.b === file,
                    gameKey: UtilitiesService.Compress.gamekey(systemKey, title, file)
                };

                catalog.entries.push(entry);
                AddCatalogEntry(catalog.titleExact, title, entry);
                AddCatalogEntry(catalog.fileExact, entry.fileBasename || file, entry);
                AddCatalogEntry(catalog.fileNormalized, NormalizeFileLookupText(entry.fileBasename || file), entry);
                if (normalizedTitle) {
                    AddCatalogEntry(catalog.titleNormalized, normalizedTitle, entry);
                }
            });
        });

        return catalog;
    };

    var AddCatalogEntry = function(index, key, entry) {

        if (!key) {
            return;
        }

        if (!index[key]) {
            index[key] = [];
        }

        index[key].push(entry);
    };

    var FindCatalogEntriesByFile = function(catalog, file) {

        var basename = NormalizeImportedRomFilename(file);
        var exactMatches = catalog.fileExact[basename] || [];
        var normalizedMatches;

        if (exactMatches.length) {
            return exactMatches.slice(0);
        }

        normalizedMatches = catalog.fileNormalized[NormalizeFileLookupText(basename)] || [];
        return normalizedMatches.slice(0);
    };

    var FindCatalogEntriesByTitle = function(catalog, title) {

        var exactMatches = catalog.titleExact[title];
        var normalizedTitle;
        var titleNames;

        if (exactMatches && exactMatches.length) {
            return {
                title: title,
                entries: exactMatches.slice(0)
            };
        }

        normalizedTitle = NormalizeTitleLookupText(title);
        titleNames = catalog.titleNamesByNormalized[normalizedTitle] || [];

        if (titleNames.length > 1) {
            return {
                ambiguous: true,
                error: 'Title "' + title + '" matched multiple catalog titles for system "' + catalog.system + '".',
                candidates: FlattenTitleCandidates(catalog, titleNames)
            };
        }

        if (titleNames.length === 1) {
            return {
                title: titleNames[0],
                entries: (catalog.titleExact[titleNames[0]] || []).slice(0)
            };
        }

        return {
            title: title,
            entries: []
        };
    };

    var FilterEntriesByTitle = function(catalog, entries, title) {

        var titleResolution = FindCatalogEntriesByTitle(catalog, title);
        var allowedTitles = {};
        var result = [];

        if (titleResolution.ambiguous) {
            return titleResolution;
        }

        for (var i = 0; i < titleResolution.entries.length; ++i) {
            allowedTitles[titleResolution.entries[i].title] = true;
        }

        for (var j = 0; j < entries.length; ++j) {
            if (allowedTitles[entries[j].title]) {
                result.push(entries[j]);
            }
        }

        return {
            entries: result
        };
    };

    var SelectPreferredTitleEntry = function(entries) {

        var best = [];

        entries = entries || [];

        if (entries.length === 1) {
            return {
                entry: entries[0]
            };
        }

        for (var i = 0; i < entries.length; ++i) {
            if (entries[i].best) {
                best.push(entries[i]);
            }
        }

        if (best.length === 1) {
            return {
                entry: best[0]
            };
        }

        return {
            ambiguous: true,
            error: 'Title matched multiple ROM files. Add the File value to disambiguate.',
            candidates: entries
        };
    };

    var BuildResolvedCatalogEntry = function(entry, matchMethod) {
        return {
            ok: true,
            system: entry.system,
            systemKey: entry.systemKey,
            title: entry.title,
            file: entry.file,
            gameKey: entry.gameKey,
            matchMethod: matchMethod || 'catalog'
        };
    };

    var BuildResolutionIssue = function(errorType, message, system, title, file, candidates) {
        return {
            ok: false,
            errorType: errorType || 'unmatched',
            error: message || 'Game could not be matched.',
            system: NormalizeImportField(system),
            title: NormalizeImportField(title),
            file: NormalizeImportedRomFilename(file),
            candidates: BuildCandidateSummaries(candidates)
        };
    };

    var BuildCandidateSummaries = function(candidates) {

        var result = [];

        candidates = candidates || [];

        for (var i = 0; i < Math.min(candidates.length, 8); ++i) {
            if (!candidates[i]) {
                continue;
            }

            result.push({
                system: candidates[i].system,
                systemKey: candidates[i].systemKey,
                title: candidates[i].title,
                file: candidates[i].file
            });
        }

        return result;
    };

    var FlattenTitleCandidates = function(catalog, titleNames) {

        var result = [];

        for (var i = 0; i < titleNames.length; ++i) {
            var entries = catalog.titleExact[titleNames[i]] || [];
            for (var j = 0; j < entries.length; ++j) {
                result.push(entries[j]);
            }
        }

        return result;
    };

    var NormalizeImportField = function(value) {
        return String(value || '').replace(/\0/g, '').replace(/[\t\r\n]+/g, ' ').replace(/\s+/g, ' ').trim();
    };

    var NormalizeImportedRomFilename = function(value) {

        value = NormalizeImportField(value).replace(/\\/g, '/');

        if (!value) {
            return '';
        }

        value = value.split(/[?#]/)[0];
        value = value.split('/').pop();
        return NormalizeImportField(value);
    };

    var NormalizeTitleLookupText = function(value) {
        return NormalizeImportField(value).toLowerCase();
    };

    var NormalizeFileLookupText = function(value) {
        return NormalizeImportedRomFilename(value).toLowerCase();
    };

    var GetSystemDisplayKey = function(systemKey) {
        return String(systemKey || '').toUpperCase();
    };

    var IsRecordActive = function(record) {

        if (!record) {
            return false;
        }

        return record.active === true || record.active === 't' || record.active === 'true' || record.active === 1 || record.active === '1';
    };

    var NormalizeBoolean = function(value, defaultValue) {

        if (typeof value === 'undefined' || value === null || value === '') {
            return defaultValue;
        }

        if (value === true || value === false) {
            return value;
        }

        value = String(value).toLowerCase().trim();

        if (value === 'true' || value === '1' || value === 'yes' || value === 'on' || value === 'published' || value === 'active' || value === 'show' || value === 'shown') {
            return true;
        }

        if (value === 'false' || value === '0' || value === 'no' || value === 'off' || value === 'hidden' || value === 'inactive' || value === 'hide') {
            return false;
        }

        return null;
    };

    var NormalizePublishedState = function(changes, currentValue) {

        if (Object.prototype.hasOwnProperty.call(changes, 'active')) {
            return NormalizeBoolean(changes.active, currentValue);
        }

        if (Object.prototype.hasOwnProperty.call(changes, 'published')) {
            return NormalizeBoolean(changes.published, currentValue);
        }

        if (Object.prototype.hasOwnProperty.call(changes, 'hidden')) {
            var hidden = NormalizeBoolean(changes.hidden, null);
            return hidden === null ? null : !hidden;
        }

        return currentValue;
    };

    var CreateValidationError = function(message, details) {

        var err = new Error(message || 'Featured collection validation failed.');
        err.isValidation = true;
        err.details = details || null;
        return err;
    };

    var ParseIntegerOrDefault = function(value, defaultValue) {

        value = parseInt(value, 10);
        return isNaN(value) ? defaultValue : value;
    };

    var ParseDateSortValue = function(value, defaultValue) {

        var date;

        if (!value) {
            return defaultValue;
        }

        date = new Date(value);

        if (isNaN(date.getTime())) {
            return defaultValue;
        }

        return date.getTime();
    };

    var ParsePositiveInteger = function(value) {

        value = parseInt(value, 10);

        if (isNaN(value) || value < 1) {
            return null;
        }

        return value;
    };

})();
